// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inaiwowobcjubchogjda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYWl3b3dvYmNqdWJjaG9namRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzUyNzAsImV4cCI6MjA2OTkxMTI3MH0.XdQvDLzdID_XWLp4rbXSa9RhRm_U1ZvwHpzPp-MZwNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});